// DO NOT EDIT — generated by scripts/audio/gen-bindings.js from asset-pipeline/manifest.json
// Run `npm run audio:codegen` (from scripts/) to regenerate.

// ---------------------------------------------------------------------------
// SFX
// ---------------------------------------------------------------------------

/**
 * All SFX keys → their asset URL.
 * Manifest SFX (18) use .mp3 paths; synth-only sounds (8) keep their .wav paths.
 * Synth-only keys: blip, select, pickup, jump, whoosh, thud, sparkle2, dazzle.
 */
export const SFX_FILES = {
  robot_alert: './sfx/robot_alert.mp3',
  robot_pursuit: './sfx/robot_pursuit.mp3',
  robot_footstep: './sfx/robot_footstep.mp3',
  panic_warning: './sfx/panic_warning.mp3',
  lockdown_alarm: './sfx/lockdown_alarm.mp3',
  lockdown_clear: './sfx/lockdown_clear.mp3',
  door_lock: './sfx/door_lock.mp3',
  gate_open: './sfx/gate_open.mp3',
  quest_progress: './sfx/quest_progress.mp3',
  quest_complete: './sfx/quest_complete.mp3',
  quest_blocked: './sfx/quest_blocked.mp3',
  food_pickup: './sfx/food_pickup.mp3',
  feed_follow: './sfx/feed_follow.mp3',
  follower_lost: './sfx/follower_lost.mp3',
  ambient_bed: './sfx/ambient_bed.mp3',
  hit: './sfx/hit.mp3',
  error: './sfx/error.mp3',
  confirm: './sfx/confirm.mp3',
  blip: './sfx/blip.wav',
  select: './sfx/select.wav',
  pickup: './sfx/pickup.wav',
  jump: './sfx/jump.wav',
  whoosh: './sfx/whoosh.wav',
  thud: './sfx/thud.wav',
  sparkle2: './sfx/sparkle2.wav',
  dazzle: './sfx/dazzle.wav',
} as const;

export type SfxName = keyof typeof SFX_FILES;

/**
 * Fallback URLs: for each manifest SFX, the committed synth WAV to use until
 * the real .mp3 is generated. audio.ts uses this to auto-degrade gracefully.
 */
export const SFX_FALLBACK: Partial<Record<SfxName, string>> = {
  robot_alert: './sfx/error.wav',
  robot_pursuit: './sfx/hit.wav',
  robot_footstep: './sfx/thud.wav',
  panic_warning: './sfx/error.wav',
  lockdown_alarm: './sfx/error.wav',
  lockdown_clear: './sfx/confirm.wav',
  door_lock: './sfx/error.wav',
  gate_open: './sfx/confirm.wav',
  quest_progress: './sfx/blip.wav',
  quest_complete: './sfx/confirm.wav',
  quest_blocked: './sfx/error.wav',
  food_pickup: './sfx/pickup.wav',
  feed_follow: './sfx/confirm.wav',
  follower_lost: './sfx/error.wav',
  ambient_bed: './sfx/blip.wav',
  hit: './sfx/hit.wav',
  error: './sfx/error.wav',
  confirm: './sfx/confirm.wav',
};

/**
 * Per-SFX default volume (0..1). Pass to playSfx() for consistent mix levels.
 */
export const SFX_VOLUME: Record<SfxName, number> = {
  robot_alert: 0.7,
  robot_pursuit: 0.6,
  robot_footstep: 0.45,
  panic_warning: 0.7,
  lockdown_alarm: 0.7,
  lockdown_clear: 0.6,
  door_lock: 0.7,
  gate_open: 0.65,
  quest_progress: 0.55,
  quest_complete: 0.7,
  quest_blocked: 0.6,
  food_pickup: 0.55,
  feed_follow: 0.6,
  follower_lost: 0.55,
  ambient_bed: 0.3,
  hit: 0.8,
  error: 0.7,
  confirm: 0.7,
  blip: 0.6,
  select: 0.6,
  pickup: 0.6,
  jump: 0.6,
  whoosh: 0.6,
  thud: 0.6,
  sparkle2: 0.6,
  dazzle: 0.6,
};

// ---------------------------------------------------------------------------
// Music
// ---------------------------------------------------------------------------

/**
 * All music keys → their asset URL (./music/<key>.mp3).
 */
export const MUSIC_FILES = {
  title_theme: './music/title_theme.mp3',
  explore_loop: './music/explore_loop.mp3',
  tension_loop: './music/tension_loop.mp3',
  panic_loop: './music/panic_loop.mp3',
  lockdown_loop: './music/lockdown_loop.mp3',
  victory_sting: './music/victory_sting.mp3',
  caught_sting: './music/caught_sting.mp3',
  ambient_bed_music: './music/ambient_bed_music.mp3',
} as const;

export type MusicName = keyof typeof MUSIC_FILES;

/**
 * Per-track playback metadata: loop flag and default volume.
 */
export const MUSIC_META: Record<MusicName, { loop: boolean; volume: number }> = {
  title_theme: { loop: true, volume: 0.5 },
  explore_loop: { loop: true, volume: 0.4 },
  tension_loop: { loop: true, volume: 0.45 },
  panic_loop: { loop: true, volume: 0.5 },
  lockdown_loop: { loop: true, volume: 0.5 },
  victory_sting: { loop: false, volume: 0.6 },
  caught_sting: { loop: false, volume: 0.6 },
  ambient_bed_music: { loop: true, volume: 0.25 },
};
